# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_sparseSCAcppFunction_rcpp_hello_world`)
}

sumC <- function(x) {
    .Call(`_sparseSCAcppFunction_sumC`, x)
}

sparseSCAcpp <- function(X, Q, RIDGE, LASSO, fixW, maxItrOuterloop, nStarts, print, tol) {
    .Call(`_sparseSCAcppFunction_sparseSCAcpp`, X, Q, RIDGE, LASSO, fixW, maxItrOuterloop, nStarts, print, tol)
}

