// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _sparseSCAcppFunction_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// sumC
double sumC(Rcpp::NumericVector x);
RcppExport SEXP _sparseSCAcppFunction_sumC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sumC(x));
    return rcpp_result_gen;
END_RCPP
}
// sparseSCAcpp
Rcpp::List sparseSCAcpp(arma::mat X, int Q, double RIDGE, arma::vec LASSO, arma::mat fixW, int maxItrOuterloop, int nStarts, bool print, double tol);
RcppExport SEXP _sparseSCAcppFunction_sparseSCAcpp(SEXP XSEXP, SEXP QSEXP, SEXP RIDGESEXP, SEXP LASSOSEXP, SEXP fixWSEXP, SEXP maxItrOuterloopSEXP, SEXP nStartsSEXP, SEXP printSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type RIDGE(RIDGESEXP);
    Rcpp::traits::input_parameter< arma::vec >::type LASSO(LASSOSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type fixW(fixWSEXP);
    Rcpp::traits::input_parameter< int >::type maxItrOuterloop(maxItrOuterloopSEXP);
    Rcpp::traits::input_parameter< int >::type nStarts(nStartsSEXP);
    Rcpp::traits::input_parameter< bool >::type print(printSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(sparseSCAcpp(X, Q, RIDGE, LASSO, fixW, maxItrOuterloop, nStarts, print, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sparseSCAcppFunction_rcpp_hello_world", (DL_FUNC) &_sparseSCAcppFunction_rcpp_hello_world, 0},
    {"_sparseSCAcppFunction_sumC", (DL_FUNC) &_sparseSCAcppFunction_sumC, 1},
    {"_sparseSCAcppFunction_sparseSCAcpp", (DL_FUNC) &_sparseSCAcppFunction_sparseSCAcpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_sparseSCAcppFunction(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
